version: "3.8"

services:

  db:
    image: postgres:16
    container_name: Server_DB
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ovpn:
    build: ./vpn_provisioner
    container_name: vpn_provisioner
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - ./vpn_provisioner:/app
      - static_volume:/usr/share/nginx/html/ovpn/staticfiles
      - media_volume:/usr/share/nginx/html/ovpn/mediafiles
    env_file:
      - ./vpn_provisioner/.env
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: [ "gunicorn" , "vpn_provisioner.wsgi:application", "--bind", "0.0.0.0:8080"]
      
  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_volume:/usr/share/nginx/html/ovpn/staticfiles
      - media_volume:/usr/share/nginx/html/ovpn/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ovpn

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
