version: "3.8"

services:

  db:
    image: postgres:16
    container_name: Server_DB
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./vpn_provisioner
    container_name: vpn_provisioner
    restart: always
    depends_on:
      - db
    volumes:
      - ./vpn_provisioner:/app
    env_file:
      - ./vpn_provisioner/.env
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: [ "gunicorn" , "vpn_provisioner.wsgi:application", "--bind", "0.0.0.0:8080"]
      
volumes:
  postgres_data:
